GYM/Models/Pago.cs
using System;
using System.Collections.Generic;

namespace GYM.Models;

public partial class Pago
{
    public int PagoId { get; set; }

    public decimal Monto { get; set; }

    public DateTime Fecha { get; set; }

    public int TipoPagoId { get; set; }

    public int UsuarioId { get; set; }

    public virtual TipoPago TipoPago { get; set; } = null!;

    public virtual Usuario Usuario { get; set; } = null!;
}

GYM/Controllers/PagosController.cs
using GYM.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;

namespace GYM.Controllers
{
    public class PagosController : Controller
    {
        private readonly GymContext _context;

        public PagosController(GymContext context)
        {
            _context = context;
        }
        // GET: PagosController
        public async Task<IActionResult> Index()
        {
            // Trae la lista de pagos junto con su TipoPago
            var pagos = await _context.Pagos.Include(p => p.TipoPago).ToListAsync();

            return View(pagos);
        }

        // GET: PagosController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PagosController/Create
        public IActionResult Create()
        {
            // Lista de tipos de pago para el dropdown
            var tipoPagos = _context.TipoPagos.ToList();
            ViewBag.TipoPagos = new SelectList(tipoPagos, "TipoPagoId", "Descripcion");
            return View();
        }

        // POST: PagosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TipoPagoId,Monto")] Pago pago)
        {
            

            if (pago.TipoPagoId != null && pago.Monto != null)
            {
                using var connection = _context.Database.GetDbConnection();
                await connection.OpenAsync();

                using var command = connection.CreateCommand();
                command.CommandText = "EXEC sp_InsertarPago @Monto, @TipoPagoId, @UsuarioId";
                command.Parameters.AddRange(new[]
                {
                    new SqlParameter("@Monto", pago.Monto),
                    new SqlParameter("@TipoPagoId", pago.TipoPagoId),
                    new SqlParameter("@UsuarioId", 1) // UsuarioId siempre es 1 según lo indicado
                });

                await command.ExecuteNonQueryAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(pago);
        }

        // GET: PagosController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PagosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PagosController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PagosController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

GYM/Views/Pagos/Create.cshtml
@model GYM.Models.Pago
@{
    ViewData["Title"] = "Crear Pago";
}

<h2>Crear Pago</h2>

<form method="post" action="@Url.Action("Create", "Pagos")">
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label>Tipo de Pago:</label>
        <select name="TipoPagoId" asp-items="@ViewBag.TipoPagos"></select>
    </div>
    <div class="form-group">
        <label>Monto:</label>
        <input type="text" name="Monto" class="form-control" />
    </div>
    <button type="submit" class="btn btn-success">Guardar</button>
</form>

GYM/Views/Pagos/Index.cshtml
@model List<GYM.Models.Pago>
@{
    ViewData["Title"] = "Pagos";
}

<h2>Pagos</h2>

<a href="@Url.Action("Create", "Pagos")">Crear Pago</a>

<table class="table">
    <thead>
        <tr>
            <th>Descripción</th>
            <th>Fecha</th>
            <th>Monto</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var pago in Model)
        {
            <tr>
                <td>@pago.TipoPago.Descripcion</td>
                <td>@pago.Fecha</td>
                <td>-@pago.Monto</td>
            </tr>
        }
    </tbody>
</table>